'use strict';
const LEVELS = [
 {name:'باغِ آرزوها',route:[[0,6],[1,6],[2,6],[2,5],[2,4],[3,4],[4,4],[4,3],[4,2],[5,2],[6,2],[6,1],[6,0]],extras:[[1,5],[3,5],[5,3]],tone:0},
 {name:'گذرِ شکوفه‌ها',route:[[0,6],[0,5],[0,4],[1,4],[2,4],[2,3],[2,2],[3,2],[4,2],[4,3],[5,3],[6,3],[6,2],[6,1],[6,0]],extras:[[1,5],[1,2],[5,1]],tone:1},
 {name:'باغِ ستاره‌ها',route:[[0,6],[1,6],[1,5],[1,4],[2,4],[3,4],[3,5],[4,5],[5,5],[5,4],[5,3],[4,3],[4,2],[4,1],[5,1],[6,1],[6,0]],extras:[[0,4],[2,5],[3,1]],tone:2}
];
const $=s=>document.querySelector(s), directions={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]};
let level=0,position=[0,6],steps=0,phase='playing',walkable=new Set(),muted=false,audioCtx,repeatTimer,delayTimer,winTimer,hintTimer,lastMove=0;
const player=$('#player'),dialog=$('#celebration'),buttons=[...document.querySelectorAll('[data-dir]')];
function audio(){if(muted)return null;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx}catch{return null}}
function tone(f,start,duration,volume,type='sine'){const ctx=audio();if(!ctx)return;const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(f,ctx.currentTime+start);gain.gain.setValueAtTime(0,ctx.currentTime+start);gain.gain.linearRampToValueAtTime(volume,ctx.currentTime+start+.008);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+start+duration);osc.connect(gain);gain.connect(ctx.destination);osc.start(ctx.currentTime+start);osc.stop(ctx.currentTime+start+duration+.01);osc.onended=()=>{osc.disconnect();gain.disconnect()}}
function footstep(){tone(steps%2?175:145,0,.075,.07,'triangle');tone(650,.035,.035,.018,'sine')}
function winSound(){[523.25,659.25,783.99,1046.5].forEach((f,i)=>tone(f,i*.13,.3,.085));tone(523.25,.43,.5,.025,'triangle')}
function setPosition(el,p){el.style.left=(7+p[0]*86/7)+'%';el.style.top=(7+p[1]*86/7)+'%'}
function renderLevel(){clearTimeout(winTimer);stopHold();phase='playing';steps=0;position=[...LEVELS[level].route[0]];walkable=new Set([...LEVELS[level].route,...LEVELS[level].extras].map(p=>p.join(',')));$('#tiles').replaceChildren();for(let y=0;y<7;y++)for(let x=0;x<7;x++){const tile=document.createElement('div');tile.className='tile'+(walkable.has(`${x},${y}`)?' path':'')+(x===0&&y===6?' start':'');tile.dataset.cell=`${x},${y}`;$('#tiles').append(tile)}setPosition(player,position);setPosition($('#goal'),[6,0]);$('#level-number').textContent=`مرحلهٔ ${(level+1).toLocaleString('fa-IR')} از ۳`;$('#level-title').textContent=LEVELS[level].name;$('#steps').textContent='۰ قدم';$('#hint').textContent='با فلش‌ها نانا رو حرکت بده.';$('#board').style.backgroundBlendMode=level===1?'soft-light':'normal';$('#board').style.backgroundColor=['#80b494','#a9b9c9','#80b494'][level];document.querySelectorAll('.level-progress li').forEach((el,i)=>{el.className=i===level?'current':i<level?'done':'';el.textContent=i<level?'✓':(i+1).toLocaleString('fa-IR');if(i===level)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current')});buttons.forEach(b=>b.disabled=false)}
function move(direction){if(phase!=='playing')return false;const delta=directions[direction];if(!delta)return false;const next=[position[0]+delta[0],position[1]+delta[1]];if(!walkable.has(next.join(','))){$('#hint').textContent='از روی سنگ‌های روشن برو ♡';clearTimeout(hintTimer);hintTimer=setTimeout(()=>{$('#hint').textContent='آروم آروم، داری می‌رسی!'},1400);return false}position=next;steps++;setPosition(player,position);$('#steps').textContent=steps.toLocaleString('fa-IR')+' قدم';document.querySelector(`[data-cell="${position.join(',')}"]`)?.classList.add('visited');player.classList.remove('walking');void player.offsetWidth;player.classList.add('walking');footstep();if(position[0]===6&&position[1]===0){phase='won';stopHold();buttons.forEach(b=>b.disabled=true);winSound();winTimer=setTimeout(showWin,250)}return true}
function confetti(){const box=$('.confetti');box.replaceChildren();for(let i=0;i<28;i++){const bit=document.createElement('i');bit.style.setProperty('--x',`${(i*37)%100}%`);bit.style.setProperty('--c',['#b59bdc','#e8bd5c','#82b299','#e4a9b9'][i%4]);bit.style.setProperty('--delay',`${(i%7)*.12}s`);box.append(bit)}}
function showWin(){dialog.classList.remove('final');$('#win-label').textContent=`مرحلهٔ ${(level+1).toLocaleString('fa-IR')} تموم شد!` ;$('#win-image').src='assets/cat-win.jpg';$('#win-image').alt='گربهٔ خوشحال که لایک نشان می‌دهد';$('#win-title').textContent='آفرین نانا ❤️';$('#win-copy').textContent=level===2?'هر سه مرحله رو رد کردی! یه پیام کوچولو منتظرته.':'دیدی تونستی؟ یه قدم نزدیک‌تر به حال خوب!';$('#next').textContent=level===2?'پیام آخر رو ببین ♡':'بریم مرحلهٔ بعد ←';dialog.showModal();confetti()}
function showFinal(){phase='finished';dialog.classList.add('final');$('#win-label').textContent='یک پیام برای نانا';$('#win-image').src='assets/cat-healthy-glasses.png';$('#win-image').alt='گربهٔ نارنجی با موهای فر مشکی، عینک گرد، پاهای سالم و یک نامه';$('#win-title').textContent='زودی خوب شو دلم برات تنگ شده';$('#win-copy').textContent='❤️';$('#next').textContent='یه بار دیگه بازی کنیم ↻';confetti()}
$('#next').addEventListener('click',()=>{audio();if(phase==='finished'){level=0;dialog.close();renderLevel();buttons[0].focus()}else if(level===2){showFinal()}else{level++;dialog.close();renderLevel();buttons[0].focus()}});
dialog.addEventListener('cancel',e=>e.preventDefault());
function stopHold(){clearTimeout(delayTimer);clearInterval(repeatTimer);buttons.forEach(b=>b.classList.remove('pressed'))}
buttons.forEach(btn=>{btn.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();stopHold();audio();btn.setPointerCapture(e.pointerId);btn.classList.add('pressed');move(btn.dataset.dir);if(phase==='playing')delayTimer=setTimeout(()=>{repeatTimer=setInterval(()=>move(btn.dataset.dir),180)},280)});btn.addEventListener('pointerup',stopHold);btn.addEventListener('pointercancel',stopHold);btn.addEventListener('lostpointercapture',stopHold);btn.addEventListener('click',e=>{if(e.detail===0){audio();move(btn.dataset.dir)}})});
const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',s:'down',a:'left',d:'right'};
window.addEventListener('keydown',e=>{if(dialog.open||e.ctrlKey||e.metaKey||e.altKey)return;const dir=keys[e.key];if(dir){e.preventDefault();audio();const now=performance.now();if(!e.repeat||now-lastMove>150){move(dir);lastMove=now}}});window.addEventListener('blur',stopHold);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopHold()});
$('#sound').addEventListener('click',()=>{muted=!muted;$('#sound').setAttribute('aria-pressed',String(!muted));$('#sound').setAttribute('aria-label',muted?'روشن کردن صدا':'قطع صدا');$('#sound-icon').textContent=muted?'♪':'♫';if(!muted){audio();tone(660,0,.1,.04)}else if(audioCtx?.state==='running')audioCtx.suspend().catch(()=>{})});
renderLevel();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'move_nana',title:'حرکت نانا',description:'Move Nana one tile up, down, left or right on the current game map.',inputSchema:{type:'object',properties:{direction:{type:'string',enum:['up','down','left','right']}},required:['direction'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Object.hasOwn(directions,input.direction))throw new Error('Invalid direction');const moved=move(input.direction);return {moved,level:level+1,position:[...position],steps,phase}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
